### ISSUE TITLE
Divide by zero in Num

### ISSUE THREAD

**Issue by feydan** [jstewmc/php-helpers#3]
https://github.com/jstewmc/php-helpers/blob/master/src/Num.php#L844

I'm using the Usps address norm library, and I'm getting some divide by zero errors on this line.  I'm assuming this is due to a dirty fraction string with $m[4] being equal to 0.  I can try to track down the dirty address that is causing this issue, but should there be protection for this exception in the logic?

**Comment by javabudd** [comment]
File has been drastically changed since this has opened, create a new ticket if needed!
